name: flutter_player
description: A Flutter player Project.
publish_to: 'none'
version: 0.2.5

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  window_manager: ^0.3.7

  desktop_drop: ^0.4.1
  file_picker: ^8.0.3

  dio: ^5.3.3
  
  easy_refresh: ^3.3.4

  #数据集
  hive: ^2.2.3
  hive_generator: ^2.0.1
  hive_flutter: ^1.1.0

  #视频播放
  media_kit: ^1.1.10 # Primary package.
  media_kit_video: ^1.2.4 # For video rendering.
  media_kit_libs_video: ^1.0.4

  # 音量、亮度控制
  flutter_volume_controller: ^1.3.1
  #screen_brightness: ^0.2.2+1

  #cookies管理
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1

  #MD5 hash
  crypto: ^3.0.3

  get: ^4.6.6
  filepicker_windows: ^2.1.3
  cached_network_image: ^3.3.1

  permission_handler: ^11.3.1
  wakelock_plus: ^1.2.5
  logger: ^2.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8

flutter:
 

  uses-material-design: true
