name: player-build-action
#推送Tag时触发
on: 
  push:
    tags:
      - 'v*.*.*'
jobs:
  # Windows 镜像
  build-android:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      # checkout 连接仓库内容
      - uses: actions/checkout@v3
        with:
          ref: main
      
      #迁移PUB_CACHE到D盘
      - name: mkdir PUB_CACHE
        run: mkdir "D:/flutter-pub"

      # 设置Flutter环境 使用flutter_action
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with: # with == arg?
          flutter-version: "3.19.x"
          cache: true
          pub-cache-key: "flutter-pub" # optional, change this to force refresh cache of dart pub get dependencies
          pub-cache-path: "D:/flutter-pub" # optional, change this to specify the cache path

      - run: echo PUB-CACHE-PATH=${{ steps.flutter-action.outputs.PUB-CACHE-PATH }}

      #keystore部署
      - name: Get Android Keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: android.jks
          encodedString: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
      #JAVA 环境部署
      - name: Setup JAVA
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"
          
      - name: Restore Packages
        run: flutter pub get

      # 3.3 设置flutter_distributor环境 用于打包发布
      - name: Install flutter_distributor
        run: dart pub global activate flutter_distributor

      # 3.4 build apk
      - name: Build Apk
        run: flutter_distributor package --platform android --targets apk --skip-clean
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD}}

      # - name: Build Windows
      #   run: flutter_distributor package --platform windows --targets zip --skip-clean

      - name: pwd
        run: dir

      # 3.5 上传ZIP
      - name: Upload Release
        uses: softprops/action-gh-release@v2 #用于直接传入到github release?
        with:
          tag_name: ${{ github.ref }}
          files: |
           ./dist/*/*.zip
           ./dist/*/*.apk
        env: 
          GITHUB_TOKEN: ${{ secrets.Tokens }}
        #完成
      - run: echo "build jobs done."
  