name: player-build-action
#推送Tag时触发
on: 
  push:
    tags:
      - 'v*.*.*'
jobs:
  # Windows 镜像
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      # checkout 连接仓库内容
      - uses: actions/checkout@v3
        with:
          ref: main
      # 设置Flutter环境 使用flutter_action
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with: # with == arg?
          flutter-version: "3.19.x"
          cache: true
      - name: Enable Flutter Desktop
        run: flutter config --enable-windows-desktop

      - name: Restore Packages
        run: flutter pub get

      # 3.3 设置flutter_distributor环境 用于打包发布
      - name: Install flutter_distributor
        run: dart pub global activate flutter_distributor

      # 3.4 build Windows zip\apk
      - name: Build Apk
        run: flutter_distributor package --platform android --targets apk --skip-clean

      - name: Build Windows
        run: flutter_distributor package --platform windows --targets zip --skip-clean

      - name: pwd
        run: dir

      # 3.5 上传ZIP
      - name: Upload Release
        uses: softprops/action-gh-release@v2 #用于直接传入到github release?
        with:
          tag_name: ${{ github.ref }}
          files: |
           ./dist/*/*.zip
           ./dist/*/*.apk
        env: 
          GITHUB_TOKEN: ${{ secrets.Tokens }}
        #完成
      - run: echo "windows jobs done."
  